# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-30 15:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pinpin', '0005_auto_20170930_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pinpin.City'),
        ),
    ]
