# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-07 05:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pinpin', '0008_follower'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follower',
            name='friend',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower', to=settings.AUTH_USER_MODEL),
        ),
    ]
