# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-07 05:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pinpin', '0009_auto_20171007_0530'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follower',
            old_name='friend',
            new_name='follower',
        ),
    ]
