# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-21 11:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_street'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=10)),
                ('street', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Street')),
            ],
        ),
    ]
