# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-21 11:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.City')),
            ],
        ),
        migrations.AddField(
            model_name='address',
            name='zipcode',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
