# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-21 13:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20170921_1252'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('user', models.ManyToManyField(blank=True, to='main.User')),
            ],
        ),
        migrations.AlterField(
            model_name='education',
            name='degree',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main.Degree'),
        ),
    ]
