# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-21 13:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20170921_1311'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video_Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage_link', models.URLField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('education', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Education')),
            ],
        ),
        migrations.CreateModel(
            name='Video_Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage_link', models.URLField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Experience')),
            ],
        ),
        migrations.CreateModel(
            name='Video_Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage_link', models.URLField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Skill')),
            ],
        ),
    ]
