# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-22 12:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_video_education_video_experience_video_skill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='zipcode',
        ),
    ]
