# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-22 12:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_remove_address_zipcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='zipcode',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
